name: 'Build Size Diff'
description: 'Automated bundle size scanning (baseline)'
author: 'Giorgi Kishmareia'

branding:
  icon: 'package'
  color: 'gray-dark'

inputs:
  build-command:
    description: 'Build command to run'
    required: false
    default: 'npm run build'
  build-timeout-minutes:
    description: 'Max minutes to allow build to run before failing'
    required: false
    default: '15'
  allow-unsafe-build:
    description: 'Allow build execution that requires a shell'
    required: false
    default: 'false'
  fail-on-stderr:
    description: 'Fail build if stderr output is non-empty'
    required: false
    default: 'false'
  dist-path:
    description: 'Output directory to scan'
    required: false
    default: 'dist'
  gzip:
    description: 'Calculate gzip sizes'
    required: false
    default: 'true'
  brotli:
    description: 'Calculate brotli sizes'
    required: false
    default: 'true'

outputs:
  total-size:
    description: 'Total bundle size in bytes'
  total-gzip:
    description: 'Total gzip size in bytes'
  total-brotli:
    description: 'Total brotli size in bytes'
  status:
    description: 'Status: pass'

runs:
  using: 'node20'
  main: 'dist/index.cjs'
